name: pubsub_nats

services:
  pubsub:
    extends:
      file: ../docker/resources.yaml
      service: wasm32
    build:
      args:
        FEATURES: http-default,messaging-nats
    depends_on:
      - nats

  nats:
    extends:
      file: ../docker/resources.yaml
      service: nats
