[package]
name = "runtime-cli"
description = "Credibil runtime"
publish = false
readme = "README.md"
default-run = "standard"
authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[[bin]]
name = "standard"
path = "src/standard.rs"

[[bin]]
name = "minimal"
path = "src/minimal.rs"

[lints]
workspace = true

[features]
default = ["jit"]
# Enables just-in-time wasm to machine code compilation.
jit = ["wasmtime/cranelift"]

[dependencies]
anyhow.workspace = true

[target.'cfg(unix)'.dependencies]
res-azkeyvault.workspace = true
res-mongodb.workspace = true
res-nats.workspace = true
runtime.workspace = true
tokio = { workspace = true, features = ["signal"] }
tracing.workspace = true
wasi-blobstore-mdb.workspace = true
wasi-http.workspace = true
wasi-keyvalue-nats.workspace = true
wasi-messaging-nats.workspace = true
wasi-otel.workspace = true
wasi-vault-az.workspace = true
wasmtime = { workspace = true, features = ["runtime"] }

# required for azure_identity, etc.
openssl = { version = "0.10", features = ["vendored"] }

[dev-dependencies]
axum = { workspace = true, features = ["macros"] }
bytes.workspace = true
http.workspace = true
opentelemetry.workspace = true
sdk-http.workspace = true
sdk-otel.workspace = true
# sdk-otel = { workspace = true, features = ["guest-export"] }
serde_json.workspace = true
tower-http.workspace = true
tracing.workspace = true
wasi.workspace = true
wit-bindgen.workspace = true
wit-bindings.workspace = true

[[example]]
name = "blobstore"
path = "examples/blobstore.rs"
crate-type = ["cdylib"]

[[example]]
name = "http"
path = "examples/http.rs"
crate-type = ["cdylib"]

[[example]]
name = "http-out"
path = "examples/http-out/lib.rs"
crate-type = ["cdylib"]

[[example]]
name = "proxy"
path = "examples/proxy/lib.rs"
crate-type = ["cdylib"]

[[example]]
name = "keyvalue"
path = "examples/keyvalue.rs"
crate-type = ["cdylib"]

[[example]]
name = "otel"
path = "examples/otel/lib.rs"
crate-type = ["cdylib"]

[[example]]
name = "pub-sub"
path = "examples/pub_sub.rs"
crate-type = ["cdylib"]

[[example]]
name = "request-reply"
path = "examples/request_reply.rs"
crate-type = ["cdylib"]

[[example]]
name = "vault"
path = "examples/vault.rs"
crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = "s"
strip = true

[package.metadata.cargo-machete]
ignored = ["openssl"]

[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
authors = ["Credibil"]
categories = ["wasm", "wasi", "runtime"]
edition = "2024"
homepage = "https://credibil.io"
keywords = ["decentralized", "identity"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/credibil/wrt"
rust-version = "1.90"
version = "0.12.0"

[workspace.lints.rust]
# https://dirname.github.io/rust-std-doc/rustc/lints/listing/allowed-by-default.html
# missing_docs = "warn"
trivial_numeric_casts = "warn"
unused_extern_crates = "warn"
unsafe_op_in_unsafe_fn = "warn"

[workspace.lints.clippy]
# https://doc.rust-lang.org/stable/clippy/index.html
all = "warn"      # correctness, suspicious, style, complexity, perf
nursery = "warn"
pedantic = "warn"
cargo = "warn"

# Cherry-picked lints are from the `restriction` lint group in order to drive up
# consistency, quality, and brevity
# See https://microsoft.github.io/rust-guidelines/guidelines/universal/index.html

# allow_attributes_without_reason = "warn"
as_pointer_underscore = "warn"
assertions_on_result_states = "warn"
clone_on_ref_ptr = "warn"
deref_by_slicing = "warn"
disallowed_script_idents = "warn"
empty_drop = "warn"
empty_enum_variants_with_brackets = "warn"
empty_structs_with_brackets = "warn"
fn_to_numeric_cast_any = "warn"
if_then_some_else_none = "warn"
map_err_ignore = "warn"
redundant_type_annotations = "warn"
renamed_function_params = "warn"
semicolon_outside_block = "warn"
undocumented_unsafe_blocks = "warn"
unnecessary_safety_comment = "warn"
unnecessary_safety_doc = "warn"
unneeded_field_pattern = "warn"
unused_result_ok = "warn"

[workspace.dependencies]
anyhow = "1.0.100"
async-nats = { version = "0.44.2" }
axum = { version = "0.8.4", default-features = false, features = ["json"] }
azure_core = "0.29.1"
azure_identity = "0.29.0"
azure_security_keyvault_secrets = "0.8.0"
base64ct = { version = "1.8.0", features = ["std"] }
bytes = "1.10.1"
cfg-if = "1.0.3"
chrono = "0.4.42"
futures = "0.3.31"
http = "1.3.1"
hyper = "1.7.0"
mongodb = "3.3.0"
nkeys = "0.4.5"
opentelemetry = "0.31.0"
opentelemetry_sdk = { version = "0.31.0", features = ["experimental_metrics_custom_reader"] }
serde = { version = "1.0.225", features = ["derive"] }
serde_json = "1.0.145"
time = "0.3.44"
tokio = { version = "1.47.1", default-features = false }
tower = "0.5.2"
tower-http = { version = "0.6.6", features = ["cors", "trace"] }
tracing = "0.1.41"
tracing-opentelemetry = "0.32.0"
tracing-subscriber = { version = "0.3.20", features = ["env-filter", "fmt"] }
wasi = "=0.14.7"
wasmtime = { version = "37.0.0", default-features = false, features = ["component-model-async"] }
wasmtime-wasi = { version = "37.0.0", features = ["p3"] }
wasmtime-wasi-http = { version = "37.0.0", features = ["p3"] }
wasmtime-wasi-io = "37.0.0"
wit-bindgen = "0.46.0"

# credibil registry
credibil-encoding = { version = "0.4.0", registry = "credibil" }
credibil-otel = { version = "0.4.0", registry = "credibil" }

# interally referenced crates
res-azkeyvault = { path = "crates/res-azkeyvault", version = "0.12.0", registry = "credibil" }
res-mongodb = { path = "crates/res-mongodb", version = "0.12.0", registry = "credibil" }
res-nats = { path = "crates/res-nats", version = "0.12.0", registry = "credibil" }
runtime = { path = "crates/runtime", version = "0.12.0", registry = "credibil" }
sdk-http = { path = "crates/sdk-http", version = "0.12.0", registry = "credibil" }
sdk-otel = { path = "crates/sdk-otel", version = "0.12.0", registry = "credibil" }
sdk-otel-attr = { path = "crates/sdk-otel-attr", version = "0.12.0", registry = "credibil" }
wasi-blobstore-mdb = { path = "crates/wasi-blobstore-mdb", version = "0.12.0", registry = "credibil" }
wasi-http = { path = "crates/wasi-http", version = "0.12.0", registry = "credibil" }
wasi-keyvalue-nats = { path = "crates/wasi-keyvalue-nats", version = "0.12.0", registry = "credibil" }
wasi-messaging-nats = { path = "crates/wasi-messaging-nats", version = "0.12.0", registry = "credibil" }
wasi-otel = { path = "crates/wasi-otel", version = "0.12.0", registry = "credibil" }
wasi-vault-az = { path = "crates/wasi-vault-az", version = "0.12.0", registry = "credibil" }
wit-bindings = { path = "crates/wit-bindings", version = "0.12.0", registry = "credibil" }

# [patch."https://github.com/credibil/core.git"]
# credibil-otel = { path = "../../credibil/core/crates/otel" }
