[package]
name = "runtime-cli"
description = "Credibil runtime"
publish = false
readme = "README.md"
authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
name = "xx"
doctest = false

[lints]
workspace = true

[features]
default = ["jit", "http-server"]

# Top-level feature sets that can be used to create a build. 
# Each set contains a unique grouping of component-resource tuples used by wasm apps.
http-server = ["http-default", "otel-default"]
credibil = ["http-default", "otel-default", "blobstore-mongodb", "keyvalue-nats", "messaging-nats", "vault-azure"]
realtime-http = ["http-default", "otel-default", "keyvalue-redis"]
realtime-messaging = ["http-default", "otel-default", "messaging-kafka", "identity-azure"]
realtime-websockets = ["http-default", "messaging-kafka", "otel-default", "websockets-default"]

# Component-Resource tuples (not intended to be used directly)
blobstore-mongodb = ["blobstore", "mongodb"]
blobstore-nats = ["blobstore", "nats"]
http-default = ["http"]
identity-azure = ["identity", "azure"]
keyvalue-nats = ["keyvalue", "nats"]
keyvalue-redis = ["keyvalue", "redis"]
messaging-nats = ["messaging", "nats"]
messaging-kafka = ["messaging", "kafka"]
otel-default = ["otel"]
sql-postgres = ["sql", "postgres"]
vault-azure = ["vault", "azure"]
websockets-default = ["websockets"]

# WASI components (not intended to be used directly)
blobstore = ["dep:wasi-blobstore"]
http = ["dep:wasi-http", "dep:wasmtime-wasi-http"]
identity = ["dep:wasi-identity"]
keyvalue = ["dep:wasi-keyvalue"]
messaging = ["dep:wasi-messaging"]
otel = ["dep:wasi-otel"]
sql = ["dep:wasi-sql"]
vault = ["dep:wasi-vault"]
websockets = ["dep:wasi-websockets"]

# Component resources (not intended to be used directly)
azure = ["dep:res-azure"]
kafka = ["dep:res-kafka"]
mongodb = ["dep:res-mongodb"]
nats = ["dep:res-nats"]
postgres = ["dep:res-postgres"]
redis = ["dep:res-redis"]

# Enables just-in-time wasm to machine code compilation.
jit = ["runtime/jit"]

[dependencies]
anyhow.workspace = true
tracing.workspace = true
wasi-blobstore = { workspace = true, optional = true }
wasi-http = { workspace = true, optional = true }
wasi-identity = { workspace = true, optional = true }
wasi-keyvalue = { workspace = true, optional = true }
wasi-messaging = { workspace = true, optional = true }
wasi-otel = { workspace = true, optional = true }
wasi-sql = { workspace = true, optional = true }
wasi-vault = { workspace = true, optional = true }
wasi-websockets = { workspace = true, optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
base64ct.workspace = true
bytes.workspace = true
futures.workspace = true
http.workspace = true
http-body-util.workspace = true
reqwest.workspace = true
res-azure = { workspace = true, optional = true }
res-mongodb = { workspace = true, optional = true }
res-kafka = { workspace = true, optional = true }
res-nats = { workspace = true, optional = true }
res-postgres = { workspace = true, optional = true }
res-redis = { workspace = true, optional = true }
runtime.workspace = true
tokio = { workspace = true, features = ["macros"] }
wasmtime.workspace = true
wasmtime-wasi.workspace = true
wasmtime-wasi-http = { workspace = true, optional = true }

# required for azure_identity, etc.
openssl = { version = "0.10.75", features = ["vendored"] }

[dev-dependencies]
axum = { workspace = true, features = ["macros"] }
base64ct.workspace = true
bytes.workspace = true
http.workspace = true
http-body-util.workspace = true
opentelemetry.workspace = true
serde_json.workspace = true
tower-http.workspace = true
wasip3.workspace = true
wit-bindgen.workspace = true

[[example]]
name = "blobstore"
path = "examples/blobstore.rs"
crate-type = ["cdylib"]
required-features = ["blobstore"]

[[example]]
name = "http"
path = "examples/http.rs"
crate-type = ["cdylib"]
required-features = ["http"]

[[example]]
name = "proxy"
path = "examples/proxy.rs"
crate-type = ["cdylib"]
required-features = ["http", "keyvalue"]

[[example]]
name = "keyvalue"
path = "examples/keyvalue.rs"
crate-type = ["cdylib"]
required-features = ["keyvalue"]

[[example]]
name = "otel"
path = "examples/otel.rs"
crate-type = ["cdylib"]
required-features = ["http", "otel"]

[[example]]
name = "pub-sub"
path = "examples/pub_sub.rs"
crate-type = ["cdylib"]
required-features = ["messaging"]

[[example]]
name = "request-reply"
path = "examples/request_reply.rs"
crate-type = ["cdylib"]
required-features = ["messaging"]

[[example]]
name = "vault"
path = "examples/vault.rs"
crate-type = ["cdylib"]
required-features = ["vault"]

[[example]]
name = "redis"
path = "examples/redis/lib.rs"
crate-type = ["cdylib"]
required-features = ["keyvalue", "redis"]

[[example]]
name = "kafka"
path = "examples/kafka/lib.rs"
crate-type = ["cdylib"]
required-features = ["messaging", "kafka"]

[[example]]
name = "websockets"
path = "examples/websockets.rs"
crate-type = ["cdylib"]
required-features = ["websockets"]

[[example]]
name = "postgres"
path = "examples/postgres/lib.rs"
crate-type = ["cdylib"]
required-features = ["sql", "postgres"]

[profile.release]
lto = true
opt-level = "s"
strip = true

[package.metadata.cargo-machete]
ignored = ["openssl"]

[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
authors = ["Credibil"]
categories = ["runtime", "wasi", "wasm"]
edition = "2024"
homepage = "https://credibil.io"
keywords = ["decentralized", "identity"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/credibil/wrt"
rust-version = "1.91"
version = "0.14.0"

[workspace.lints.rust]
# https://dirname.github.io/rust-std-doc/rustc/lints/listing/allowed-by-default.html
# missing_docs = "warn"
trivial_numeric_casts = "warn"
unsafe_op_in_unsafe_fn = "warn"
unused_extern_crates = "warn"

[workspace.lints.clippy]
# https://doc.rust-lang.org/stable/clippy/index.html
all = "warn"      # correctness, suspicious, style, complexity, perf
cargo = "warn"
nursery = "warn"
pedantic = "warn"

# Cherry-picked lints are from the `restriction` lint group in order to drive up
# consistency, quality, and brevity
# See https://microsoft.github.io/rust-guidelines/guidelines/universal/index.html

# allow_attributes_without_reason = "warn"
as_pointer_underscore = "warn"
assertions_on_result_states = "warn"
clone_on_ref_ptr = "warn"
deref_by_slicing = "warn"
disallowed_script_idents = "warn"
empty_drop = "warn"
empty_enum_variants_with_brackets = "warn"
empty_structs_with_brackets = "warn"
fn_to_numeric_cast_any = "warn"
if_then_some_else_none = "warn"
map_err_ignore = "warn"
redundant_type_annotations = "warn"
renamed_function_params = "warn"
semicolon_outside_block = "warn"
undocumented_unsafe_blocks = "warn"
unnecessary_safety_comment = "warn"
unnecessary_safety_doc = "warn"
unneeded_field_pattern = "warn"
unused_result_ok = "warn"

[workspace.dependencies]
anyhow = "1.0.100"
async-nats = { version = "0.45.0" }
axum = { version = "0.8.4", default-features = false, features = ["json"] }
azure_core = "0.29.1"
azure_identity = "0.29.0"
azure_security_keyvault_secrets = "0.8.0"
base64ct = { version = "1.8.0", features = ["std"] }
bytes = "1.10.1"
cfg-if = "1.0.3"
chrono = "0.4.42"
csv = "1.4.0"
fromenv = "0.1.0"
futures = "0.3.31"
futures-channel = "0.3.31"
futures-util = "0.3.31"
http = "1.3.1"
http-body-util = "0.1.3"
hyper = "1.7.0"
hyper-tungstenite = "0.19.0"
hyper-util = "0.1.17"
jsonschema = "0.33.0"
mongodb = "3.3.0"
nkeys = "0.4.5"
opentelemetry = "0.31.0"
opentelemetry_sdk = { version = "0.31.0", features = ["experimental_metrics_custom_reader"] }
proc-macro2 = "1.0.101"
quote = "1.0.40"
rdkafka = { version = "0.38", features = ["cmake-build", "ssl-vendored", "tokio"] }
redis = { version = "0.32.6", features = ["aio", "connection-manager", "tokio-comp"] }
reqwest = "0.12.24"
schema-registry-client = "0.4.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
syn = { version = "2.0.106", features = ["parsing"] }
time = "0.3.44"
tokio = { version = "1.47.1", default-features = false }
tokio-tungstenite = "0.28.0"
tower = "0.5.2"
tower-http = { version = "0.6.6", features = ["cors", "trace"] }
tracing = "0.1.41"
tracing-opentelemetry = "0.32.0"
tracing-subscriber = { version = "0.3.20", features = ["env-filter", "fmt"] }
tungstenite = "0.28.0"
wasip3 = { version = "0.2.1", features = ["http-compat"] }
wasmtime = { version = "38.0.3", default-features = false, features = ["component-model-async"] }
wasmtime-wasi = { version = "38.0.3", features = ["p3"] }
wasmtime-wasi-http = { version = "38.0.3", features = ["p3"] }
wasmtime-wasi-io = "38.0.3"
wit-bindgen = { version = "0.46.0" }

# credibil registry
credibil-encoding = { version = "0.4.0", registry = "credibil" }
credibil-otel = { version = "0.4.0", registry = "credibil" }

# interally referenced crates
res-azure = { path = "crates/res-azure", version = "0.14.0", registry = "credibil" }
res-kafka = { path = "crates/res-kafka", version = "0.14.0", registry = "credibil" }
res-mongodb = { path = "crates/res-mongodb", version = "0.14.0", registry = "credibil" }
res-nats = { path = "crates/res-nats", version = "0.14.0", registry = "credibil" }
res-postgres = { path = "crates/res-postgres", version = "0.14.0", registry = "credibil" }
res-redis = { path = "crates/res-redis", version = "0.14.0", registry = "credibil" }
runtime = { path = "crates/runtime", version = "0.14.0", registry = "credibil" }
wasi-blobstore = { path = "crates/wasi-blobstore", version = "0.14.0", registry = "credibil" }
wasi-http = { path = "crates/wasi-http", version = "0.14.0", registry = "credibil" }
wasi-identity = { path = "crates/wasi-identity", version = "0.14.0", registry = "credibil" }
wasi-keyvalue = { path = "crates/wasi-keyvalue", version = "0.14.0", registry = "credibil" }
wasi-messaging = { path = "crates/wasi-messaging", version = "0.14.0", registry = "credibil" }
wasi-otel = { path = "crates/wasi-otel", version = "0.14.0", registry = "credibil" }
wasi-otel-attr = { path = "crates/wasi-otel-attr", version = "0.14.0", registry = "credibil" }
wasi-sql = { path = "crates/wasi-sql", version = "0.14.0", registry = "credibil" }
wasi-vault = { path = "crates/wasi-vault", version = "0.14.0", registry = "credibil" }
wasi-websockets = { path = "crates/wasi-websockets", version = "0.14.0", registry = "credibil" }

# [patch."https://github.com/credibil/core.git"]
# credibil-otel = { path = "../../credibil/core/crates/otel" }
