[toolchain]
channel = "nightly-2025-12-08"
# channel = "stable"
components = ["clippy", "rust-src", "rustfmt"]
targets = [
  "aarch64-apple-darwin",
  "wasm32-wasip2",
]
# profile = "minimal" # "default"
