name: pub-sub-nats

secrets:
  credibil:
    environment: CARGO_REGISTRIES_CREDIBIL_TOKEN

services:
  pubsub:
    image: pub-sub-nats:latest
    container_name: pub-sub-nats
    env_file: ../../.env
    build:
      context: ../..
      dockerfile: Dockerfile
      secrets:
        - credibil
      args:
        FEATURES: http-default,messaging-nats,keyvalue-nats
    volumes:
       - ../../target/wasm32-wasip2/release/examples/pub_sub.wasm:/app.wasm
    ports:
      - 8080:8080
    depends_on:
      - nats

  nats:
    image: nats:latest
    platform: linux/arm64
    ports:
      - 4222:4222
    command: ["-js"]
