services:
  # Create Kafka topics from the KAFKA_TOPICS environment variable
  # N.B. named "kafka" so users can infer the dependency from the compose file name
  kafka:
    image: apache/kafka:latest
    command: |
      bash -c '
        for topic in $${KAFKA_TOPICS//,/ }; do
          /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:29092 --create --if-not-exists --topic $$topic;
        done
      '
    environment:
      KAFKA_TOPICS: ${KAFKA_TOPICS}
    depends_on:
      broker:
        condition: service_healthy

  # Kafka broker and controller configuration
  broker:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
    healthcheck:
      test: nc -z kafka 9092 || exit 1
      interval: 5s
      timeout: 10s
      retries: 5
