
# cargo-vet audits file

[audits]

[[trusted.aho-corasick]]
criteria = "safe-to-deploy"
user-id = 189               # Andrew Gallant (BurntSushi)
start = "2019-03-28"
end = "2026-09-11"

[[trusted.anstream]]
criteria = "safe-to-deploy"
user-id = 6743              # Ed Page (epage)
start = "2023-03-16"
end = "2026-09-11"

[[trusted.anstyle]]
criteria = "safe-to-deploy"
user-id = 6743              # Ed Page (epage)
start = "2022-05-18"
end = "2026-09-11"

[[trusted.anstyle-parse]]
criteria = "safe-to-deploy"
user-id = 6743              # Ed Page (epage)
start = "2023-03-08"
end = "2026-09-11"

[[trusted.anstyle-query]]
criteria = "safe-to-deploy"
user-id = 6743              # Ed Page (epage)
start = "2023-04-13"
end = "2026-09-11"

[[trusted.anstyle-wincon]]
criteria = "safe-to-deploy"
user-id = 6743              # Ed Page (epage)
start = "2023-03-08"
end = "2026-09-11"

[[trusted.anyhow]]
criteria = "safe-to-deploy"
user-id = 3618              # David Tolnay (dtolnay)
start = "2019-10-05"
end = "2026-09-11"

[[trusted.async-trait]]
criteria = "safe-to-deploy"
user-id = 3618              # David Tolnay (dtolnay)
start = "2019-07-23"
end = "2026-09-11"

[[trusted.backtrace]]
criteria = "safe-to-deploy"
user-id = 55123             # rust-lang-owner
start = "2025-05-06"
end = "2026-09-11"

[[trusted.bytes]]
criteria = "safe-to-deploy"
user-id = 6741              # Alice Ryhl (Darksonn)
start = "2021-01-11"
end = "2026-09-11"

[[trusted.cap-fs-ext]]
criteria = "safe-to-deploy"
user-id = 6825              # Dan Gohman (sunfishcode)
start = "2020-12-11"
end = "2026-09-11"

[[trusted.cap-net-ext]]
criteria = "safe-to-deploy"
user-id = 6825              # Dan Gohman (sunfishcode)
start = "2023-04-07"
end = "2026-09-11"

[[trusted.cap-primitives]]
criteria = "safe-to-deploy"
user-id = 6825              # Dan Gohman (sunfishcode)
start = "2020-08-07"
end = "2026-09-11"

[[trusted.cap-rand]]
criteria = "safe-to-deploy"
user-id = 6825              # Dan Gohman (sunfishcode)
start = "2020-09-24"
end = "2026-09-11"

[[trusted.cap-std]]
criteria = "safe-to-deploy"
user-id = 6825              # Dan Gohman (sunfishcode)
start = "2020-06-25"
end = "2026-09-11"

[[trusted.cap-time-ext]]
criteria = "safe-to-deploy"
user-id = 6825              # Dan Gohman (sunfishcode)
start = "2020-09-21"
end = "2026-09-11"

[[trusted.cc]]
criteria = "safe-to-deploy"
user-id = 55123             # rust-lang-owner
start = "2022-10-29"
end = "2026-09-11"

[[trusted.clap]]
criteria = "safe-to-deploy"
user-id = 6743              # Ed Page (epage)
start = "2021-12-08"
end = "2026-09-11"

[[trusted.clap_builder]]
criteria = "safe-to-deploy"
user-id = 6743              # Ed Page (epage)
start = "2023-03-28"
end = "2026-09-11"

[[trusted.clap_derive]]
criteria = "safe-to-deploy"
user-id = 6743              # Ed Page (epage)
start = "2021-12-08"
end = "2026-09-11"

[[trusted.clap_lex]]
criteria = "safe-to-deploy"
user-id = 6743              # Ed Page (epage)
start = "2022-04-15"
end = "2026-09-11"

[[trusted.colorchoice]]
criteria = "safe-to-deploy"
user-id = 6743              # Ed Page (epage)
start = "2023-04-13"
end = "2026-09-11"

[[trusted.derive_more]]
criteria = "safe-to-deploy"
user-id = 3797              # Jelte Fennema-Nio (JelteF)
start = "2019-05-25"
end = "2026-09-11"

[[trusted.dyn-clone]]
criteria = "safe-to-deploy"
user-id = 3618              # David Tolnay (dtolnay)
start = "2019-12-23"
end = "2026-09-11"

[[trusted.errno]]
criteria = "safe-to-deploy"
user-id = 6825              # Dan Gohman (sunfishcode)
start = "2023-08-29"
end = "2026-09-11"

[[trusted.fd-lock]]
criteria = "safe-to-deploy"
user-id = 6825              # Dan Gohman (sunfishcode)
start = "2022-01-21"
end = "2026-09-11"

[[trusted.ff]]
criteria = "safe-to-deploy"
user-id = 6289              # Jack Grigg (str4d)
start = "2021-08-11"
end = "2026-09-11"

[[trusted.find-msvc-tools]]
criteria = "safe-to-deploy"
user-id = 539               # Josh Stone (cuviper)
start = "2025-08-29"
end = "2026-09-11"

[[trusted.flate2]]
criteria = "safe-to-deploy"
user-id = 980               # Sebastian Thiel (Byron)
start = "2023-08-15"
end = "2026-09-11"

[[trusted.form_urlencoded]]
criteria = "safe-to-deploy"
user-id = 1139              # Manish Goregaokar (Manishearth)
start = "2021-02-19"
end = "2026-09-11"

[[trusted.fs-set-times]]
criteria = "safe-to-deploy"
user-id = 6825              # Dan Gohman (sunfishcode)
start = "2020-09-15"
end = "2026-09-11"

[[trusted.group]]
criteria = "safe-to-deploy"
user-id = 1244              # ebfull
start = "2019-10-08"
end = "2026-09-11"

[[trusted.h2]]
criteria = "safe-to-deploy"
user-id = 359               # Sean McArthur (seanmonstar)
start = "2019-03-13"
end = "2026-09-11"

[[trusted.hashbrown]]
criteria = "safe-to-deploy"
user-id = 55123             # rust-lang-owner
start = "2025-04-30"
end = "2026-09-11"

[[trusted.http]]
criteria = "safe-to-deploy"
user-id = 359               # Sean McArthur (seanmonstar)
start = "2019-04-05"
end = "2026-09-11"

[[trusted.http-body-util]]
criteria = "safe-to-deploy"
user-id = 359               # Sean McArthur (seanmonstar)
start = "2022-10-25"
end = "2026-09-11"

[[trusted.httparse]]
criteria = "safe-to-deploy"
user-id = 359               # Sean McArthur (seanmonstar)
start = "2019-07-03"
end = "2026-09-11"

[[trusted.hyper]]
criteria = "safe-to-deploy"
user-id = 359               # Sean McArthur (seanmonstar)
start = "2019-03-01"
end = "2026-09-11"

[[trusted.hyper-tls]]
criteria = "safe-to-deploy"
user-id = 359               # Sean McArthur (seanmonstar)
start = "2019-03-19"
end = "2026-09-11"

[[trusted.hyper-util]]
criteria = "safe-to-deploy"
user-id = 359               # Sean McArthur (seanmonstar)
start = "2022-01-15"
end = "2026-09-11"

[[trusted.idna]]
criteria = "safe-to-deploy"
user-id = 1139              # Manish Goregaokar (Manishearth)
start = "2024-07-01"
end = "2026-09-11"

[[trusted.indexmap]]
criteria = "safe-to-deploy"
user-id = 539               # Josh Stone (cuviper)
start = "2020-01-15"
end = "2026-09-11"

[[trusted.io-extras]]
criteria = "safe-to-deploy"
user-id = 6825              # Dan Gohman (sunfishcode)
start = "2021-11-09"
end = "2026-09-11"

[[trusted.io-lifetimes]]
criteria = "safe-to-deploy"
user-id = 6825              # Dan Gohman (sunfishcode)
start = "2021-06-12"
end = "2026-09-11"

[[trusted.is_terminal_polyfill]]
criteria = "safe-to-deploy"
user-id = 6743              # Ed Page (epage)
start = "2024-05-02"
end = "2026-09-11"

[[trusted.js-sys]]
criteria = "safe-to-deploy"
user-id = 1                 # Alex Crichton (alexcrichton)
start = "2019-03-04"
end = "2026-09-11"

[[trusted.libc]]
criteria = "safe-to-deploy"
user-id = 55123             # rust-lang-owner
start = "2024-08-15"
end = "2026-09-11"

[[trusted.libm]]
criteria = "safe-to-deploy"
user-id = 55123             # rust-lang-owner
start = "2024-10-26"
end = "2026-09-11"

[[trusted.linux-raw-sys]]
criteria = "safe-to-deploy"
user-id = 6825              # Dan Gohman (sunfishcode)
start = "2021-06-12"
end = "2026-09-11"

[[trusted.lock_api]]
criteria = "safe-to-deploy"
user-id = 2915              # Amanieu d'Antras (Amanieu)
start = "2019-05-04"
end = "2026-09-11"

[[trusted.mach2]]
criteria = "safe-to-deploy"
user-id = 51017             # Yuki Okushi (JohnTitor)
start = "2021-11-15"
end = "2026-09-11"

[[trusted.memchr]]
criteria = "safe-to-deploy"
user-id = 189               # Andrew Gallant (BurntSushi)
start = "2019-07-07"
end = "2026-09-11"

[[trusted.mime]]
criteria = "safe-to-deploy"
user-id = 359               # Sean McArthur (seanmonstar)
start = "2019-09-09"
end = "2026-09-11"

[[trusted.mio]]
criteria = "safe-to-deploy"
user-id = 6025              # Thomas de Zeeuw (Thomasdezeeuw)
start = "2019-12-17"
end = "2026-09-11"

[[trusted.once_cell_polyfill]]
criteria = "safe-to-deploy"
user-id = 6743              # Ed Page (epage)
start = "2025-05-22"
end = "2026-09-11"

[[trusted.openssl-probe]]
criteria = "safe-to-deploy"
user-id = 1                 # Alex Crichton (alexcrichton)
start = "2020-08-04"
end = "2026-09-11"

[[trusted.openssl-src]]
criteria = "safe-to-deploy"
user-id = 1                 # Alex Crichton (alexcrichton)
start = "2019-02-25"
end = "2026-09-11"

[[trusted.parking_lot]]
criteria = "safe-to-deploy"
user-id = 2915              # Amanieu d'Antras (Amanieu)
start = "2019-05-04"
end = "2026-09-11"

[[trusted.parking_lot_core]]
criteria = "safe-to-deploy"
user-id = 2915              # Amanieu d'Antras (Amanieu)
start = "2019-05-04"
end = "2026-09-11"

[[trusted.potential_utf]]
criteria = "safe-to-deploy"
user-id = 1139              # Manish Goregaokar (Manishearth)
start = "2024-11-23"
end = "2026-09-11"

[[trusted.prettyplease]]
criteria = "safe-to-deploy"
user-id = 3618              # David Tolnay (dtolnay)
start = "2022-01-04"
end = "2026-09-11"

[[trusted.proc-macro2]]
criteria = "safe-to-deploy"
user-id = 3618              # David Tolnay (dtolnay)
start = "2019-04-23"
end = "2026-09-11"

[[trusted.ref-cast]]
criteria = "safe-to-deploy"
user-id = 3618              # David Tolnay (dtolnay)
start = "2019-05-05"
end = "2026-09-11"

[[trusted.ref-cast-impl]]
criteria = "safe-to-deploy"
user-id = 3618              # David Tolnay (dtolnay)
start = "2019-05-05"
end = "2026-09-11"

[[trusted.regex]]
criteria = "safe-to-deploy"
user-id = 189               # Andrew Gallant (BurntSushi)
start = "2019-02-27"
end = "2026-09-11"

[[trusted.regex-automata]]
criteria = "safe-to-deploy"
user-id = 189               # Andrew Gallant (BurntSushi)
start = "2019-02-25"
end = "2026-09-11"

[[trusted.regex-syntax]]
criteria = "safe-to-deploy"
user-id = 189               # Andrew Gallant (BurntSushi)
start = "2019-03-30"
end = "2026-09-11"

[[trusted.reqwest]]
criteria = "safe-to-deploy"
user-id = 359               # Sean McArthur (seanmonstar)
start = "2019-03-04"
end = "2026-09-11"

[[trusted.rustc-demangle]]
criteria = "safe-to-deploy"
user-id = 55123             # rust-lang-owner
start = "2023-03-23"
end = "2026-09-11"

[[trusted.rustix]]
criteria = "safe-to-deploy"
user-id = 6825              # Dan Gohman (sunfishcode)
start = "2021-10-29"
end = "2026-09-11"

[[trusted.rustversion]]
criteria = "safe-to-deploy"
user-id = 3618              # David Tolnay (dtolnay)
start = "2019-07-08"
end = "2026-09-11"

[[trusted.ryu]]
criteria = "safe-to-deploy"
user-id = 3618              # David Tolnay (dtolnay)
start = "2019-05-02"
end = "2026-09-11"

[[trusted.scopeguard]]
criteria = "safe-to-deploy"
user-id = 2915              # Amanieu d'Antras (Amanieu)
start = "2020-02-16"
end = "2026-09-11"

[[trusted.serde_bytes]]
criteria = "safe-to-deploy"
user-id = 3618              # David Tolnay (dtolnay)
start = "2019-02-25"
end = "2026-09-11"

[[trusted.serde_json]]
criteria = "safe-to-deploy"
user-id = 3618              # David Tolnay (dtolnay)
start = "2019-02-28"
end = "2026-09-11"

[[trusted.serde_path_to_error]]
criteria = "safe-to-deploy"
user-id = 3618              # David Tolnay (dtolnay)
start = "2019-08-20"
end = "2026-09-11"

[[trusted.serde_repr]]
criteria = "safe-to-deploy"
user-id = 3618              # David Tolnay (dtolnay)
start = "2019-04-26"
end = "2026-09-11"

[[trusted.slab]]
criteria = "safe-to-deploy"
user-id = 6741              # Alice Ryhl (Darksonn)
start = "2021-10-13"
end = "2026-09-11"

[[trusted.smallvec]]
criteria = "safe-to-deploy"
user-id = 2017              # Matt Brubeck (mbrubeck)
start = "2019-10-28"
end = "2026-09-11"

[[trusted.socket2]]
criteria = "safe-to-deploy"
user-id = 6025              # Thomas de Zeeuw (Thomasdezeeuw)
start = "2020-09-09"
end = "2026-09-11"

[[trusted.syn]]
criteria = "safe-to-deploy"
user-id = 3618              # David Tolnay (dtolnay)
start = "2019-03-01"
end = "2026-09-11"

[[trusted.system-interface]]
criteria = "safe-to-deploy"
user-id = 6825              # Dan Gohman (sunfishcode)
start = "2020-10-27"
end = "2026-09-11"

[[trusted.target-lexicon]]
criteria = "safe-to-deploy"
user-id = 6825              # Dan Gohman (sunfishcode)
start = "2019-03-06"
end = "2026-09-11"

[[trusted.termcolor]]
criteria = "safe-to-deploy"
user-id = 189               # Andrew Gallant (BurntSushi)
start = "2019-06-04"
end = "2026-09-11"

[[trusted.thiserror]]
criteria = "safe-to-deploy"
user-id = 3618              # David Tolnay (dtolnay)
start = "2019-10-09"
end = "2026-09-11"

[[trusted.thiserror-impl]]
criteria = "safe-to-deploy"
user-id = 3618              # David Tolnay (dtolnay)
start = "2019-10-09"
end = "2026-09-11"

[[trusted.tokio]]
criteria = "safe-to-deploy"
user-id = 6741              # Alice Ryhl (Darksonn)
start = "2020-12-25"
end = "2026-09-11"

[[trusted.tokio-macros]]
criteria = "safe-to-deploy"
user-id = 6741              # Alice Ryhl (Darksonn)
start = "2020-10-26"
end = "2026-09-11"

[[trusted.tokio-util]]
criteria = "safe-to-deploy"
user-id = 6741              # Alice Ryhl (Darksonn)
start = "2021-01-12"
end = "2026-09-11"

[[trusted.tower]]
criteria = "safe-to-deploy"
user-id = 359               # Sean McArthur (seanmonstar)
start = "2024-09-09"
end = "2026-09-11"

[[trusted.tower-http]]
criteria = "safe-to-deploy"
user-id = 359               # Sean McArthur (seanmonstar)
start = "2024-09-23"
end = "2026-09-11"

[[trusted.tower-layer]]
criteria = "safe-to-deploy"
user-id = 10                # Carl Lerche (carllerche)
start = "2019-04-27"
end = "2026-09-11"

[[trusted.unicode-ident]]
criteria = "safe-to-deploy"
user-id = 3618              # David Tolnay (dtolnay)
start = "2021-10-02"
end = "2026-09-11"

[[trusted.unicode-properties]]
criteria = "safe-to-deploy"
user-id = 1139              # Manish Goregaokar (Manishearth)
start = "2023-07-27"
end = "2026-09-11"

[[trusted.url]]
criteria = "safe-to-deploy"
user-id = 1139              # Manish Goregaokar (Manishearth)
start = "2021-02-18"
end = "2026-09-11"

[[trusted.valuable]]
criteria = "safe-to-deploy"
user-id = 10                # Carl Lerche (carllerche)
start = "2022-01-03"
end = "2026-09-11"

[[trusted.wasi]]
criteria = "safe-to-deploy"
user-id = 1                 # Alex Crichton (alexcrichton)
start = "2020-06-03"
end = "2026-09-11"

[[trusted.wasm-bindgen]]
criteria = "safe-to-deploy"
user-id = 1                 # Alex Crichton (alexcrichton)
start = "2019-03-04"
end = "2026-09-11"

[[trusted.wasm-bindgen-backend]]
criteria = "safe-to-deploy"
user-id = 1                 # Alex Crichton (alexcrichton)
start = "2019-03-04"
end = "2026-09-11"

[[trusted.wasm-bindgen-futures]]
criteria = "safe-to-deploy"
user-id = 1                 # Alex Crichton (alexcrichton)
start = "2019-03-04"
end = "2026-09-11"

[[trusted.wasm-bindgen-macro]]
criteria = "safe-to-deploy"
user-id = 1                 # Alex Crichton (alexcrichton)
start = "2019-03-04"
end = "2026-09-11"

[[trusted.wasm-bindgen-macro-support]]
criteria = "safe-to-deploy"
user-id = 1                 # Alex Crichton (alexcrichton)
start = "2019-03-04"
end = "2026-09-11"

[[trusted.wasm-bindgen-shared]]
criteria = "safe-to-deploy"
user-id = 1                 # Alex Crichton (alexcrichton)
start = "2019-03-04"
end = "2026-09-11"

[[trusted.wasm-encoder]]
criteria = "safe-to-deploy"
user-id = 73222             # wasmtime-publish
start = "2024-02-15"
end = "2026-09-11"

[[trusted.wasmparser]]
criteria = "safe-to-deploy"
user-id = 73222             # wasmtime-publish
start = "2024-02-15"
end = "2026-09-11"

[[trusted.wasmprinter]]
criteria = "safe-to-deploy"
user-id = 73222             # wasmtime-publish
start = "2024-02-15"
end = "2026-09-11"

[[trusted.web-sys]]
criteria = "safe-to-deploy"
user-id = 1                 # Alex Crichton (alexcrichton)
start = "2019-03-04"
end = "2026-09-11"

[[trusted.winapi-util]]
criteria = "safe-to-deploy"
user-id = 189               # Andrew Gallant (BurntSushi)
start = "2020-01-11"
end = "2026-09-11"

[[trusted.windows-core]]
criteria = "safe-to-deploy"
user-id = 64539             # Kenny Kerr (kennykerr)
start = "2021-11-15"
end = "2026-09-11"

[[trusted.windows-implement]]
criteria = "safe-to-deploy"
user-id = 64539             # Kenny Kerr (kennykerr)
start = "2022-01-27"
end = "2026-09-11"

[[trusted.windows-interface]]
criteria = "safe-to-deploy"
user-id = 64539             # Kenny Kerr (kennykerr)
start = "2022-02-18"
end = "2026-09-11"

[[trusted.windows-link]]
criteria = "safe-to-deploy"
user-id = 64539             # Kenny Kerr (kennykerr)
start = "2024-07-17"
end = "2026-09-11"

[[trusted.windows-registry]]
criteria = "safe-to-deploy"
user-id = 64539             # Kenny Kerr (kennykerr)
start = "2024-02-15"
end = "2026-09-11"

[[trusted.windows-result]]
criteria = "safe-to-deploy"
user-id = 64539             # Kenny Kerr (kennykerr)
start = "2024-02-02"
end = "2026-09-11"

[[trusted.windows-strings]]
criteria = "safe-to-deploy"
user-id = 64539             # Kenny Kerr (kennykerr)
start = "2024-02-02"
end = "2026-09-11"

[[trusted.windows-sys]]
criteria = "safe-to-deploy"
user-id = 64539             # Kenny Kerr (kennykerr)
start = "2021-11-15"
end = "2026-09-11"

[[trusted.windows-targets]]
criteria = "safe-to-deploy"
user-id = 64539             # Kenny Kerr (kennykerr)
start = "2022-09-09"
end = "2026-09-11"

[[trusted.windows_aarch64_gnullvm]]
criteria = "safe-to-deploy"
user-id = 64539             # Kenny Kerr (kennykerr)
start = "2022-09-01"
end = "2026-09-11"

[[trusted.windows_aarch64_msvc]]
criteria = "safe-to-deploy"
user-id = 64539             # Kenny Kerr (kennykerr)
start = "2021-11-05"
end = "2026-09-11"

[[trusted.windows_i686_gnu]]
criteria = "safe-to-deploy"
user-id = 64539             # Kenny Kerr (kennykerr)
start = "2021-10-28"
end = "2026-09-11"

[[trusted.windows_i686_gnullvm]]
criteria = "safe-to-deploy"
user-id = 64539             # Kenny Kerr (kennykerr)
start = "2024-04-02"
end = "2026-09-11"

[[trusted.windows_i686_msvc]]
criteria = "safe-to-deploy"
user-id = 64539             # Kenny Kerr (kennykerr)
start = "2021-10-27"
end = "2026-09-11"

[[trusted.windows_x86_64_gnu]]
criteria = "safe-to-deploy"
user-id = 64539             # Kenny Kerr (kennykerr)
start = "2021-10-28"
end = "2026-09-11"

[[trusted.windows_x86_64_gnullvm]]
criteria = "safe-to-deploy"
user-id = 64539             # Kenny Kerr (kennykerr)
start = "2022-09-01"
end = "2026-09-11"

[[trusted.windows_x86_64_msvc]]
criteria = "safe-to-deploy"
user-id = 64539             # Kenny Kerr (kennykerr)
start = "2021-10-27"
end = "2026-09-11"

[[trusted.winx]]
criteria = "safe-to-deploy"
user-id = 6825              # Dan Gohman (sunfishcode)
start = "2019-08-20"
end = "2026-09-11"

[[trusted.wit-parser]]
criteria = "safe-to-deploy"
user-id = 73222             # wasmtime-publish
start = "2024-02-15"
end = "2026-09-11"

[[trusted.witx]]
criteria = "safe-to-deploy"
user-id = 1                 # Alex Crichton (alexcrichton)
start = "2021-06-22"
end = "2026-09-11"
