[package]
name = "http"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow.workspace = true
axum.workspace = true
serde_json.workspace = true
tracing.workspace = true
wasi-http.workspace = true
wasi-otel.workspace = true
wasip3.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
kernel.workspace = true
tokio.workspace = true
buildgen.workspace = true
futures.workspace = true
wasmtime.workspace = true
wasmtime-wasi.workspace = true
