[package]
name = "wasi-otel"
description = "Wasm Opentelemetry WIT implementation"
readme = "README.md"
authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[features]
default = ["metrics", "tracing"]
# Export signals directly from the wasm guest rather than the host.
# guest-export = ["dep:async-trait", "dep:bytes", "dep:http", "dep:opentelemetry-http", "dep:opentelemetry-otlp"]
metrics = []
tracing = ["dep:tracing-opentelemetry", "dep:tracing-subscriber"]

[dependencies]
anyhow.workspace = true
opentelemetry.workspace = true
opentelemetry_sdk.workspace = true
tracing.workspace = true
tracing-opentelemetry = { workspace = true, optional = true }

# host dependencies
[target.'cfg(unix)'.dependencies]
credibil-otel.workspace = true
futures.workspace = true
hex = "0.4.3"
http.workspace = true
opentelemetry-proto = "0.31.0"
prost = "0.14.1"
reqwest = "0.12.23"
runtime.workspace = true
wasmtime.workspace = true

# guest dependencies
[target.'cfg(target_arch = "wasm32")'.dependencies]
cfg-if.workspace = true
num-traits = "0.2"
sdk-otel-attr.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"], optional = true }
wit-bindgen.workspace = true
