[package]
name = "wasi-keyvalue"
description = "WASI Keyvalue implementation"
readme = "README.md"
authors.workspace = true
categories.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lints]
workspace = true

[features]

# dependencies shared across host and guest
[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true

# host dependencies
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
async-nats.workspace = true
base64ct.workspace = true
futures.workspace = true
runtime.workspace = true
tracing.workspace = true
wasmtime.workspace = true
wasmtime-wasi.workspace = true

# guest dependencies
[target.'cfg(target_arch = "wasm32")'.dependencies]
wit-bindgen.workspace = true
