name: Publish Release

on:
  workflow_dispatch:

jobs:
  # skip:
  #   name: Skipped
  #   if: ${{ !startsWith(github.ref_name, 'release-') }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: |
  #         echo "This workflow only runs on the 'release-*' branches"
  #         exit 1

  # ci:
  #   name: CI
  #   if: ${{ startsWith(github.ref_name, 'release-') }}
  #   uses: credibil/pipeline/.github/workflows/ci.yaml@main
  #   secrets: inherit
  #   # with:
  #   #   outdated: prost

  # publish:
  #   name: Publish
  #   needs: ci
  #   uses: credibil/pipeline/.github/workflows/publish.yaml@main

  # crates:
  #   name: Publish crates
  #   needs: publish
  #   uses: credibil/pipeline/.github/workflows/crates.yaml@main
  #   secrets: inherit

  package:
    name: Package
    # needs: publish
    runs-on: ${{ matrix.platform == 'linux/amd64' && 'ubuntu-latest' || 'ubuntu-24.04-arm' }}
    strategy:
      matrix:
        feature: [realtime-http, realtime-messaging, realtime-websockets]
        platform: [linux/amd64, linux/arm64]
    outputs:
      sources: ${{ steps.source.outputs.json }}
    permissions:
      contents: read
      packages: write

    steps:
      - uses: credibil/pipeline/.github/actions/cargo-cache@main
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.feature }}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        id: build
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: ${{ matrix.platform }}
          build-args: |
            FEATURES=${{ matrix.feature }}
          secrets: |
            credibil=${{ secrets.CARGO_REGISTRIES_CREDIBIL_TOKEN }}
          # tags: |
          #   ${{ env.IMAGE_NAME }}:latest
          #   ${{ env.IMAGE_NAME }}:0.14.0
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-to: type=gha,scope=${{ matrix.feature }}-${{ matrix.platform }},mode=max
          cache-from: type=gha,scope=${{ matrix.feature }}-${{ matrix.platform }}
        # env:
        #   IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/${{ matrix.feature }}

      # ${{ env.IMAGE_NAME }}:${{ needs.publish.outputs.version }}

      - name: Export image source
        uses: beacon-biosignals/matrix-output@v1
        id: source
        with:
          yaml: |
            ${{ matrix.feature }}: ghcr.io/${{ github.repository_owner }}/${{ matrix.feature }}@${{ steps.build.outputs.digest }}

  # Create and push manifests for each image. This job resolves an issue GitHub
  # has with matrix builds for multi-arch images where the architecture of the
  # last image is shown as 'unknown/unknown'.
  manifest:
    name: Manifest
    needs: package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        feature: [realtime-http, realtime-messaging, realtime-websockets]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Select image sources
        id: select
        run: |
          SOURCES=$(echo '${{ needs.package.outputs.sources }}' | jq -r '.[]."${{ matrix.feature }}" | select(. != null)')
          {
            echo 'sources<<EOF'
            echo "${SOURCES}"
            echo EOF
          } >> $GITHUB_OUTPUT

      - name: Get image metadata
        uses: docker/metadata-action@v5
        id: metadata
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ matrix.feature }}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Docker manifest
        uses: int128/docker-manifest-create-action@v2
        id: build
        with:
          index-annotations: ${{ steps.metadata.outputs.labels }}
          tags: ${{ steps.metadata.outputs.tags }}
          sources: |
            ${{ steps.select.outputs.sources }}
