name: Publish Release

on:
  workflow_dispatch:

jobs:
  skip:
    name: Skipped
    if: ${{ !startsWith(github.ref_name, 'release-') }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "This workflow only runs on the 'release-*' branches"
          exit 1

  ci:
    name: CI
    if: ${{ startsWith(github.ref_name, 'release-') }}
    uses: credibil/pipeline/.github/workflows/ci.yaml@main
    secrets: inherit

  publish:
    name: Publish
    needs: ci
    uses: credibil/pipeline/.github/workflows/publish.yaml@main

  crates:
    name: Publish crates
    needs: publish
    uses: credibil/pipeline/.github/workflows/crates.yaml@main
    secrets: inherit

  package:
    name: Package
    needs: publish
    runs-on: ${{ matrix.platform == 'linux/amd64' && 'ubuntu-latest' || 'ubuntu-24.04-arm' }}
    strategy:
      matrix:
        bin: [realtime, realtime-http, realtime-websockets]
        platform: [linux/amd64, linux/arm64]
    outputs:
      sources: ${{ steps.source.outputs.json }}
    permissions:
      contents: read
      packages: write

    steps:
      - uses: credibil/pipeline/.github/actions/cargo-cache@main
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Generate metadata (tags and labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=semver,pattern={{version}},value=v${{ needs.publish.outputs.version }}
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.bin }}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        id: build
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: ${{ matrix.platform }}
          build-args: |
            BIN=${{ matrix.bin }}
          secrets: |
            credibil=${{ secrets.CARGO_REGISTRIES_CREDIBIL_TOKEN }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-to: type=gha,scope=${{ matrix.bin }}-${{ matrix.platform }},mode=max
          cache-from: type=gha,scope=${{ matrix.bin }}-${{ matrix.platform }}

      - name: Export image source
        uses: beacon-biosignals/matrix-output@v1
        id: source
        with:
          yaml: |
            ${{ matrix.bin }}: ghcr.io/${{ github.repository_owner }}/${{ matrix.bin }}@${{ steps.build.outputs.digest }}

  # Create and push manifests for each image. This job resolves an issue GitHub
  # has with matrix builds for multi-arch images where the architecture of the
  # last image is shown as 'unknown/unknown'.
  manifest:
    name: Manifest
    needs: [publish, package]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bin: [realtime, realtime-http, realtime-websockets]
    permissions:
      contents: read
      packages: write

    steps:
      - name: Select image sources
        id: select
        run: |
          SOURCES=$(echo '${{ needs.package.outputs.sources }}' | jq -r '.[]."${{ matrix.bin }}" | select(. != null)')
          {
            echo 'sources<<EOF'
            echo "${SOURCES}"
            echo EOF
          } >> $GITHUB_OUTPUT

      - name: Generate metadata
        uses: docker/metadata-action@v5
        id: metadata
        with:
          tags: |
            type=semver,pattern={{version}},value=v${{ needs.publish.outputs.version }}
          images: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.bin }}

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Docker manifest
        uses: int128/docker-manifest-create-action@v2
        id: build
        with:
          index-annotations: ${{ steps.metadata.outputs.labels }}
          tags: ${{ steps.metadata.outputs.tags }}
          sources: |
            ${{ steps.select.outputs.sources }}
