name: Publish Release

on:
  workflow_dispatch:

jobs:
  # skip:
  #   name: Skipped
  #   if: ${{ !startsWith(github.ref_name, 'release-') }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: |
  #         echo "This workflow only runs on the 'release-*' branches"
  #         exit 1

  # ci:
  #   name: CI
  #   if: ${{ startsWith(github.ref_name, 'release-') }}
  #   uses: credibil/pipeline/.github/workflows/ci.yaml@main
  #   secrets: inherit
  #   with:
  #     outdated: prost

  # publish:
  #   name: Publish
  #   needs: ci
  #   uses: credibil/pipeline/.github/workflows/publish.yaml@main

  # crates:
  #   name: Publish crates
  #   needs: publish
  #   uses: credibil/pipeline/.github/workflows/crates.yaml@main
  #   secrets: inherit

  package:
    name: Package
    # needs: publish
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:
          - name: linux/amd64
            os: ubuntu-latest
          - name: linux/arm64
            os: ubuntu-24.04-arm
        feature: [realtime-http, realtime-messaging, realtime-websockets]
    outputs:
      json: ${{ steps.digest.outputs.json }}
    permissions:
      contents: read
      packages: write

    steps:
      - uses: credibil/pipeline/.github/actions/cargo-cache@main
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        id: build
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: ${{ matrix.platform.name }}
          build-args: |
            FEATURES=${{ matrix.feature }}
          secrets: |
            credibil=${{ secrets.CARGO_REGISTRIES_CREDIBIL_TOKEN }}
          tags: |
            ${{ env.IMAGE_NAME }}:latest
          cache-to: type=gha,scope=${{ env.IMAGE_NAME }}-${{ matrix.platform.name }},mode=max
          cache-from: type=gha,scope=${{ env.IMAGE_NAME }}-${{ matrix.platform.name }}
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-${{ matrix.feature }}

          # ${{ env.IMAGE_NAME }}:${{ needs.publish.outputs.version }}

      - uses: beacon-biosignals/matrix-output@v1
        id: digest
        with:
          yaml: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-${{ matrix.feature }}: ${{ steps.build.outputs.digest }}

  manifest:
    name: Manifest
    needs: package
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - run: |
          echo "${{ needs.package.outputs.json}}"

      - run: |
          echo "${{ fromJSON(needs.package.outputs.json)[0] }}"
          echo "${{ fromJSON(needs.package.outputs.json)[1] }}"
          echo "${{ fromJSON(needs.package.outputs.json)[2] }}"

      # - uses: int128/docker-manifest-create-action@v2
      #   with:
      #     tags: ${{ env.IMAGE_NAME }}:latest
      #     sources: |
      #       ${{ fromJSON(needs.package.outputs.json)[0].source }}
      #       ${{ fromJSON(needs.package.outputs.json)[1].source }}
      #       ${{ fromJSON(needs.package.outputs.json)[2].source }}
      #       ${{ fromJSON(needs.package.outputs.json)[3].source }}
      #       ${{ fromJSON(needs.package.outputs.json)[4].source }}
      #       ${{ fromJSON(needs.package.outputs.json)[5].source }}


    