name: Publish Release

on:
  workflow_dispatch:

jobs:
  # skip:
  #   name: Skipped
  #   if: ${{ !startsWith(github.ref_name, 'release-') }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: |
  #         echo "This workflow only runs on the 'release-*' branches"
  #         exit 1

  # ci:
  #   name: CI
  #   if: ${{ startsWith(github.ref_name, 'release-') }}
  #   uses: credibil/pipeline/.github/workflows/ci.yaml@main
  #   secrets: inherit
  #   with:
  #     outdated: prost

  # publish:
  #   name: Publish
  #   needs: ci
  #   uses: credibil/pipeline/.github/workflows/publish.yaml@main

  # crates:
  #   name: Publish crates
  #   needs: publish
  #   uses: credibil/pipeline/.github/workflows/crates.yaml@main
  #   secrets: inherit

  package:
    name: Package
    # needs: publish
    # runs-on: ubuntu-latest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
        # platform: [linux/amd64, linux/arm64]
        feature: [realtime-http, realtime-messaging, realtime-websockets]
    permissions:
      contents: read
      packages: write

    steps:
      - uses: credibil/pipeline/.github/actions/cargo-cache@main
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: ${{ env.PLATFORM }}
          build-args: |
            FEATURES=${{ matrix.feature }}
          secrets: |
            credibil=${{ secrets.CARGO_REGISTRIES_CREDIBIL_TOKEN }}
          tags: |
            ${{ env.IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache,mode=max
          provenance: false # disable to avoid last build being named 'unknown/unknown'
          # sbom: false       # as above
          outputs: type=image,name=target
        env:
          PLATFORM: ${{ matrix.os == 'ubuntu-latest' && 'linux/amd64' || 'linux/arm64' }}
          IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-${{ matrix.feature }}

          # ${{ env.IMAGE_NAME }}:${{ needs.publish.outputs.version }}

      # ---------------------------------------------------
      # Local cache (alternative to Docker registry cache)
      # ---------------------------------------------------
      # - name: Cache Docker layers
      #   uses: actions/cache@v4
      #   with:
      #     path: /tmp/.buildx-cache
      #     key: ${{ runner.os }}-buildx-${{ github.sha }}
      #     restore-keys: |
      #       ${{ runner.os }}-buildx-

      # - name: Build and push image
      #   uses: docker/build-push-action@v6
      #   with:
      #     cache-from: type=local,src=/tmp/.buildx-cache
      #     cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
