name: Publish Release

on:
  workflow_dispatch:

jobs:
  # skip:
  #   name: Skipped
  #   if: ${{ !startsWith(github.ref_name, 'release-') }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: |
  #         echo "This workflow only runs on the 'release-*' branches"
  #         exit 1

  # ci:
  #   name: CI
  #   if: ${{ startsWith(github.ref_name, 'release-') }}
  #   uses: credibil/pipeline/.github/workflows/ci.yaml@main
  #   secrets: inherit
  #   with:
  #     outdated: prost

  # publish:
  #   name: Publish
  #   needs: ci
  #   uses: credibil/pipeline/.github/workflows/publish.yaml@main

  # crates:
  #   name: Publish crates
  #   needs: publish
  #   uses: credibil/pipeline/.github/workflows/crates.yaml@main
  #   secrets: inherit

  package:
    name: Package
    # needs: publish
    runs-on: ${{ matrix.platform.name == 'linux/amd64' && 'ubuntu-latest' || 'ubuntu-24.04-arm' }}
    strategy:
      matrix:
        feature: [realtime-http, realtime-messaging, realtime-websockets]
        platform: [linux/amd64, linux/arm64]
    outputs:
      json: ${{ steps.digest.outputs.json }}
    permissions:
      contents: read
      packages: write

    steps:
      - uses: credibil/pipeline/.github/actions/cargo-cache@main
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        id: build
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: ${{ matrix.platform }}
          build-args: |
            FEATURES=${{ matrix.feature }}
          secrets: |
            credibil=${{ secrets.CARGO_REGISTRIES_CREDIBIL_TOKEN }}
          tags: |
            ${{ env.IMAGE_NAME }}:latest
          cache-to: type=gha,scope=${{ env.IMAGE_NAME }}-${{ matrix.platform }},mode=max
          cache-from: type=gha,scope=${{ env.IMAGE_NAME }}-${{ matrix.platform }}
        env:
          IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/${{ matrix.feature }}

          # ${{ env.IMAGE_NAME }}:${{ needs.publish.outputs.version }}

      - name: Export image digest
        uses: beacon-biosignals/matrix-output@v1
        id: digest
        with:
          yaml: |
            ${{ matrix.feature }}: ghcr.io/${{ github.repository_owner }}/${{ matrix.feature }}@${{ steps.build.outputs.digest }}

  # Create and push manifests for each image. This job resolves an issue GitHub
  # has with matrix builds for multi-arch images where the architecture of the
  # last image is shown as 'unknown/unknown'.
  manifest:
    name: Manifest
    needs: package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        feature: [realtime-http, realtime-messaging, realtime-websockets]
    permissions:
      contents: read
      packages: write

    steps:
      - id: filter
        run: |
          echo '${{ needs.package.outputs.json }}' | jq '.[]."${{ matrix.feature }}"'

      # echo ("${{ needs.package.outputs.json }}")

      # SOURCES=$(echo "${{ needs.package.outputs.json }}" | jq '.[]."${{ matrix.feature }}" | select(. != null)')
      # echo "SOURCES: ${SOURCES}"  
      # echo "sources=${SOURCES}" >> $GITHUB_OUTPUT

      # - uses: docker/login-action@v3
      #   with:
      #     registry: https://ghcr.io
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - uses: docker/metadata-action@v5
      #   id: metadata
      #   with:
      #     images: ghcr.io/${{ github.repository_owner }}/${{ matrix.feature }}

      # - uses: int128/docker-manifest-create-action@v2
      #   id: build
      #   with:
      #     tags: ${{ steps.metadata.outputs.tags }}
      #     sources: |
      #       ${{ steps.filter.outputs.sources }}

      #       ghcr.io/${{ github.repository_owner }}/${{ matrix.feature }}@${{ needs.amd64.outputs.digest }}
      #       ghcr.io/${{ github.repository_owner }}/${{ matrix.feature }}@${{ needs.arm64.outputs.digest }}








      # - uses: int128/docker-manifest-create-action@v2
      #   with:
      #     tags: ${{ fromJSON(needs.package.outputs.json)[0].image }}:latest
      #     sources: |
      #       ${{ fromJSON(needs.package.outputs.json)[0].image }}@${{ fromJSON(needs.package.outputs.json)[0].digest }}
      #       ${{ fromJSON(needs.package.outputs.json)[0].image }}@${{ fromJSON(needs.package.outputs.json)[1].digest }}

      # - uses: int128/docker-manifest-create-action@v2
      #   with:
      #     tags: ${{ fromJSON(needs.package.outputs.json)[2].image }}:latest
      #     sources: |
      #       ${{ fromJSON(needs.package.outputs.json)[2].image }}@${{ fromJSON(needs.package.outputs.json)[2].digest }}
      #       ${{ fromJSON(needs.package.outputs.json)[2].image }}@${{ fromJSON(needs.package.outputs.json)[3].digest }}

      # - uses: int128/docker-manifest-create-action@v2
      #   with:
      #     tags: ${{ fromJSON(needs.package.outputs.json)[4].image }}:latest
      #     sources: |
      #       ${{ fromJSON(needs.package.outputs.json)[4].image }}@${{ fromJSON(needs.package.outputs.json)[4].digest }}
      #       ${{ fromJSON(needs.package.outputs.json)[4].image }}@${{ fromJSON(needs.package.outputs.json)[5].digest }}
